/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number | string;
                    PageSize?: number | string;
                    SortField?: string;
                    SortDescending?: boolean;
                    NormalizedPage?: number | string;
                    NormalizedPageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfAdminUserDto"];
                        "application/json": components["schemas"]["PagedResultOfAdminUserDto"];
                        "text/json": components["schemas"]["PagedResultOfAdminUserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number | string;
                    PageSize?: number | string;
                    SortField?: string;
                    SortDescending?: boolean;
                    NormalizedPage?: number | string;
                    NormalizedPageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfAdminRoleDto"];
                        "application/json": components["schemas"]["PagedResultOfAdminRoleDto"];
                        "text/json": components["schemas"]["PagedResultOfAdminRoleDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number | string;
                    PageSize?: number | string;
                    SortField?: string;
                    SortDescending?: boolean;
                    NormalizedPage?: number | string;
                    NormalizedPageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfAdminPermissionDto"];
                        "application/json": components["schemas"]["PagedResultOfAdminPermissionDto"];
                        "text/json": components["schemas"]["PagedResultOfAdminPermissionDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/roles/{roleId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRolePermissionsRequestDto"];
                    "text/json": components["schemas"]["UpdateRolePermissionsRequestDto"];
                    "application/*+json": components["schemas"]["UpdateRolePermissionsRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminRoleDto"];
                        "application/json": components["schemas"]["AdminRoleDto"];
                        "text/json": components["schemas"]["AdminRoleDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequestDto"];
                    "text/json": components["schemas"]["LoginRequestDto"];
                    "application/*+json": components["schemas"]["LoginRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponseDto"];
                        "application/json": components["schemas"]["LoginResponseDto"];
                        "text/json": components["schemas"]["LoginResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/quotations/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    unitId?: string;
                    includeDraft?: boolean;
                    fromDate?: string;
                    toDate?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                    SortField?: string;
                    SortDescending?: boolean;
                    NormalizedPage?: number | string;
                    NormalizedPageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponseOfQuotationPipelineResponseDto"];
                        "application/json": components["schemas"]["DashboardResponseOfQuotationPipelineResponseDto"];
                        "text/json": components["schemas"]["DashboardResponseOfQuotationPipelineResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/quotations/conversion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    unitId?: string;
                    fromDate?: string;
                    toDate?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                    SortField?: string;
                    SortDescending?: boolean;
                    NormalizedPage?: number | string;
                    NormalizedPageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponseOfConversionResponseDto"];
                        "application/json": components["schemas"]["DashboardResponseOfConversionResponseDto"];
                        "text/json": components["schemas"]["DashboardResponseOfConversionResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/quotations/aging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    unitId?: string;
                    includeDraft?: boolean;
                    fromDate?: string;
                    toDate?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                    SortField?: string;
                    SortDescending?: boolean;
                    NormalizedPage?: number | string;
                    NormalizedPageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponseOfAgingResponseDto"];
                        "application/json": components["schemas"]["DashboardResponseOfAgingResponseDto"];
                        "text/json": components["schemas"]["DashboardResponseOfAgingResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/quotations/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    unitId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponseOfQuotationSummaryDto"];
                        "application/json": components["schemas"]["DashboardResponseOfQuotationSummaryDto"];
                        "text/json": components["schemas"]["DashboardResponseOfQuotationSummaryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/quotations/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitOptionDto"][];
                        "application/json": components["schemas"]["UnitOptionDto"][];
                        "text/json": components["schemas"]["UnitOptionDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/quotations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponseOfQuotationDetailDto"];
                        "application/json": components["schemas"]["DashboardResponseOfQuotationDetailDto"];
                        "text/json": components["schemas"]["DashboardResponseOfQuotationDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminPermissionDto: {
            permissionCode: string;
            roleNames: string[];
        };
        AdminRoleDto: {
            /** Format: uuid */
            roleId: string;
            roleName: string;
            /** Format: int32 */
            userCount: number | string;
            permissionCodes: string[];
        };
        AdminUserDto: {
            /** Format: uuid */
            userId: string;
            email: string;
            displayName: string;
            roleName: string;
            isActive: boolean;
            unitNames: string[];
        };
        AgedQuotationDto: {
            /** Format: uuid */
            quotationId: string;
            quotationNo: string;
            buyerName: string;
            unitName: string;
            /** Format: double */
            valueUsd: number | string;
            /** Format: int32 */
            daysOpen: number | string;
            status: string;
            riskLevel: string;
        };
        AgingBucketDto: {
            bucket: string;
            /** Format: int32 */
            count: number | string;
            /** Format: double */
            valueUsd: number | string;
        };
        AgingKpisDto: {
            /** Format: double */
            totalOpenValueUsd: number | string;
            /** Format: double */
            highRiskAgedValueUsd: number | string;
        };
        AgingResponseDto: {
            kpis: components["schemas"]["AgingKpisDto"];
            agingBuckets: components["schemas"]["AgingBucketDto"][];
            riskLevels: components["schemas"]["RiskLevelBucketDto"][];
            agedQuotations: components["schemas"]["PagedResultOfAgedQuotationDto"];
        };
        BuyerPerformanceDto: {
            buyerName: string;
            /** Format: int32 */
            quotationsCount: number | string;
            /** Format: int32 */
            wonCount: number | string;
            /** Format: int32 */
            lostCount: number | string;
            /** Format: double */
            conversionRatePct: number | string;
            /** Format: double */
            valueUsd: number | string;
        };
        ConversionKpisDto: {
            /** Format: double */
            conversionRatePct: number | string;
            /** Format: double */
            wonValueUsd: number | string;
            /** Format: double */
            lostValueUsd: number | string;
            /** Format: double */
            avgConversionDays: number | string;
            /** Format: int32 */
            wonCount: number | string;
            /** Format: int32 */
            lostCount: number | string;
        };
        ConversionResponseDto: {
            kpis: components["schemas"]["ConversionKpisDto"];
            monthlyTrend: components["schemas"]["MonthlyTrendEntryDto"][];
            buyerPerformance: components["schemas"]["PagedResultOfBuyerPerformanceDto"];
        };
        DashboardResponseOfAgingResponseDto: {
            data: null | components["schemas"]["AgingResponseDto"];
            /** Format: date-time */
            lastRefresh: string;
        };
        DashboardResponseOfConversionResponseDto: {
            data: null | components["schemas"]["ConversionResponseDto"];
            /** Format: date-time */
            lastRefresh: string;
        };
        DashboardResponseOfQuotationDetailDto: {
            data: null | components["schemas"]["QuotationDetailDto"];
            /** Format: date-time */
            lastRefresh: string;
        };
        DashboardResponseOfQuotationPipelineResponseDto: {
            data: null | components["schemas"]["QuotationPipelineResponseDto"];
            /** Format: date-time */
            lastRefresh: string;
        };
        DashboardResponseOfQuotationSummaryDto: {
            data: null | components["schemas"]["QuotationSummaryDto"];
            /** Format: date-time */
            lastRefresh: string;
        };
        LoginRequestDto: {
            email: string;
            password: string;
        };
        LoginResponseDto: {
            token: string;
            /** Format: date-time */
            expiresAtUtc: string;
            displayName: string;
        };
        MonthlyTrendEntryDto: {
            month: string;
            /** Format: double */
            conversionRatePct: number | string;
            /** Format: int32 */
            wonCount: number | string;
            /** Format: int32 */
            lostCount: number | string;
        };
        OpenQuotationDto: {
            /** Format: uuid */
            quotationId: string;
            quotationNo: string;
            buyerName: string;
            merchandiserName: string;
            unitName: string;
            /** Format: double */
            valueUsd: number | string;
            status: string;
            /** Format: int32 */
            daysOpen: number | string;
        };
        PagedResultOfAdminPermissionDto: {
            items: components["schemas"]["AdminPermissionDto"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PagedResultOfAdminRoleDto: {
            items: components["schemas"]["AdminRoleDto"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PagedResultOfAdminUserDto: {
            items: components["schemas"]["AdminUserDto"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PagedResultOfAgedQuotationDto: {
            items: components["schemas"]["AgedQuotationDto"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PagedResultOfBuyerPerformanceDto: {
            items: components["schemas"]["BuyerPerformanceDto"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PagedResultOfOpenQuotationDto: {
            items: components["schemas"]["OpenQuotationDto"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PipelineKpisDto: {
            /** Format: int32 */
            openQuotationsCount: number | string;
            /** Format: double */
            pipelineValueUsd: number | string;
            /** Format: int32 */
            pendingApprovalCount: number | string;
            /** Format: double */
            avgDaysOpen: number | string;
        };
        QuotationDetailDto: {
            /** Format: uuid */
            quotationId: string;
            quotationNo: string;
            /** Format: date */
            quotationDate: string;
            buyerName: string;
            merchandiserName: string;
            unitName: string;
            styleNo: string;
            season: string;
            currencyCode: string;
            /** Format: double */
            quotationValueUsd: number | string;
            incoterm: string;
            paymentTerm: string;
            /** Format: date */
            validUntil: string;
            /** Format: double */
            discountUsd: number | string;
            /** Format: double */
            subtotalUsd: number | string;
            status: string;
            /** Format: date-time */
            statusDate: string;
            /** Format: int32 */
            daysInStatus: number | string;
            /** Format: int32 */
            daysOpen: number | string;
            convertedToSoNo: null | string;
            /** Format: date-time */
            convertedDate: null | string;
            /** Format: int32 */
            conversionDays: null | number | string;
            lostReason: null | string;
            /** Format: uuid */
            createdBy: string;
            items: components["schemas"]["QuotationItemDto"][];
            statusHistory: components["schemas"]["QuotationStatusHistoryDto"][];
        };
        QuotationItemDto: {
            styleNo: string;
            itemDescription: string;
            /** Format: int32 */
            qty: number | string;
            /** Format: double */
            unitPrice: number | string;
            /** Format: double */
            amount: number | string;
        };
        QuotationPipelineResponseDto: {
            kpis: components["schemas"]["PipelineKpisDto"];
            statusFunnel: components["schemas"]["StatusFunnelEntryDto"][];
            openQuotations: components["schemas"]["PagedResultOfOpenQuotationDto"];
        };
        QuotationStatusHistoryDto: {
            status: string;
            /** Format: date-time */
            statusDate: string;
        };
        QuotationSummaryDto: {
            /** Format: double */
            openPipelineValueUsd: number | string;
            /** Format: double */
            conversionRateMtdPct: number | string;
            /** Format: int32 */
            highValueAgedAlertCount: number | string;
        };
        RiskLevelBucketDto: {
            riskLevel: string;
            /** Format: int32 */
            count: number | string;
            /** Format: double */
            valueUsd: number | string;
        };
        StatusFunnelEntryDto: {
            status: string;
            /** Format: int32 */
            count: number | string;
            /** Format: double */
            valueUsd: number | string;
        };
        UnitOptionDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        UpdateRolePermissionsRequestDto: {
            permissionCodes: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
