/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sales/quotations/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    unitId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponseOfQuotationPipelineDto"];
                        "application/json": components["schemas"]["DashboardResponseOfQuotationPipelineDto"];
                        "text/json": components["schemas"]["DashboardResponseOfQuotationPipelineDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/quotations/conversion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    unitId?: string;
                    fromDate?: string;
                    toDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponseOfConversionDto"];
                        "application/json": components["schemas"]["DashboardResponseOfConversionDto"];
                        "text/json": components["schemas"]["DashboardResponseOfConversionDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/quotations/aging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    unitId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponseOfAgingDto"];
                        "application/json": components["schemas"]["DashboardResponseOfAgingDto"];
                        "text/json": components["schemas"]["DashboardResponseOfAgingDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/quotations/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    unitId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponseOfQuotationSummaryDto"];
                        "application/json": components["schemas"]["DashboardResponseOfQuotationSummaryDto"];
                        "text/json": components["schemas"]["DashboardResponseOfQuotationSummaryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/quotations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponseOfQuotationDetailDto"];
                        "application/json": components["schemas"]["DashboardResponseOfQuotationDetailDto"];
                        "text/json": components["schemas"]["DashboardResponseOfQuotationDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgedQuotationDto: {
            /** Format: uuid */
            quotationId: string;
            quotationNo: string;
            buyerName: string;
            /** Format: double */
            valueUsd: number | string;
            /** Format: int32 */
            daysOpen: number | string;
            status: string;
            riskLevel: string;
        };
        AgingBucketDto: {
            bucket: string;
            /** Format: int32 */
            count: number | string;
            /** Format: double */
            valueUsd: number | string;
        };
        AgingDto: {
            kpis: components["schemas"]["AgingKpisDto"];
            agingBuckets: components["schemas"]["AgingBucketDto"][];
            agedQuotations: components["schemas"]["AgedQuotationDto"][];
        };
        AgingKpisDto: {
            /** Format: double */
            totalOpenValueUsd: number | string;
            /** Format: double */
            highRiskAgedValueUsd: number | string;
        };
        BuyerPerformanceDto: {
            buyerName: string;
            /** Format: int32 */
            quotationsCount: number | string;
            /** Format: int32 */
            wonCount: number | string;
            /** Format: int32 */
            lostCount: number | string;
            /** Format: double */
            conversionRatePct: number | string;
            /** Format: double */
            valueUsd: number | string;
        };
        ConversionDto: {
            kpis: components["schemas"]["ConversionKpisDto"];
            monthlyTrend: components["schemas"]["MonthlyTrendEntryDto"][];
            buyerPerformance: components["schemas"]["BuyerPerformanceDto"][];
        };
        ConversionKpisDto: {
            /** Format: double */
            conversionRatePct: number | string;
            /** Format: double */
            wonValueUsd: number | string;
            /** Format: double */
            lostValueUsd: number | string;
            /** Format: double */
            avgConversionDays: number | string;
        };
        DashboardResponseOfAgingDto: {
            data: null | components["schemas"]["AgingDto"];
            /** Format: date-time */
            lastRefresh: string;
        };
        DashboardResponseOfConversionDto: {
            data: null | components["schemas"]["ConversionDto"];
            /** Format: date-time */
            lastRefresh: string;
        };
        DashboardResponseOfQuotationDetailDto: {
            data: null | components["schemas"]["QuotationDetailDto"];
            /** Format: date-time */
            lastRefresh: string;
        };
        DashboardResponseOfQuotationPipelineDto: {
            data: null | components["schemas"]["QuotationPipelineDto"];
            /** Format: date-time */
            lastRefresh: string;
        };
        DashboardResponseOfQuotationSummaryDto: {
            data: null | components["schemas"]["QuotationSummaryDto"];
            /** Format: date-time */
            lastRefresh: string;
        };
        MonthlyTrendEntryDto: {
            month: string;
            /** Format: double */
            conversionRatePct: number | string;
        };
        OpenQuotationDto: {
            /** Format: uuid */
            quotationId: string;
            quotationNo: string;
            buyerName: string;
            merchandiserName: string;
            /** Format: double */
            valueUsd: number | string;
            status: string;
            /** Format: int32 */
            daysOpen: number | string;
        };
        PipelineKpisDto: {
            /** Format: int32 */
            openQuotationsCount: number | string;
            /** Format: double */
            pipelineValueUsd: number | string;
            /** Format: int32 */
            pendingApprovalCount: number | string;
            /** Format: double */
            avgDaysOpen: number | string;
        };
        QuotationDetailDto: {
            /** Format: uuid */
            quotationId: string;
            quotationNo: string;
            /** Format: date */
            quotationDate: string;
            buyerName: string;
            merchandiserName: string;
            unitName: string;
            styleNo: string;
            season: string;
            currencyCode: string;
            /** Format: double */
            quotationValueUsd: number | string;
            incoterm: string;
            paymentTerm: string;
            /** Format: date */
            validUntil: string;
            /** Format: double */
            discountUsd: number | string;
            /** Format: double */
            subtotalUsd: number | string;
            status: string;
            /** Format: date-time */
            statusDate: string;
            /** Format: int32 */
            daysInStatus: number | string;
            /** Format: int32 */
            daysOpen: number | string;
            convertedToSoNo: null | string;
            /** Format: date-time */
            convertedDate: null | string;
            /** Format: int32 */
            conversionDays: null | number | string;
            lostReason: null | string;
            /** Format: uuid */
            createdBy: string;
            items: components["schemas"]["QuotationItemDto"][];
            statusHistory: components["schemas"]["QuotationStatusHistoryDto"][];
        };
        QuotationItemDto: {
            styleNo: string;
            itemDescription: string;
            /** Format: int32 */
            qty: number | string;
            /** Format: double */
            unitPrice: number | string;
            /** Format: double */
            amount: number | string;
        };
        QuotationPipelineDto: {
            kpis: components["schemas"]["PipelineKpisDto"];
            statusFunnel: components["schemas"]["StatusFunnelEntryDto"][];
            openQuotations: components["schemas"]["OpenQuotationDto"][];
        };
        QuotationStatusHistoryDto: {
            status: string;
            /** Format: date-time */
            statusDate: string;
        };
        QuotationSummaryDto: {
            /** Format: double */
            openPipelineValueUsd: number | string;
            /** Format: double */
            conversionRateMtdPct: number | string;
            /** Format: int32 */
            highValueAgedAlertCount: number | string;
        };
        StatusFunnelEntryDto: {
            status: string;
            /** Format: int32 */
            count: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
